import './styles.css';

const workflow = ['Lead','Proposal Created','Proposal Sent','Proposal Accepted','Agreement Signed','Advance Payment Received','Requirement Collection','Design Approval','Development','Testing','Client Review','Revision','Final Payment','Website Deployment','Source Code Handover','Project Completion Certificate','7 Days Support','Project Closed'];
const modules = ['Dashboard','Clients','Proposals','Agreements','Requirements','Design Approval','Projects','Payments','Files','Communication','Delivery','Support','Reports','Settings'];
const statuses = ['Lead','Proposal Sent','Accepted','Advance Received','Design','Development','Testing','Revision','Completed','Delivered','Support'];
let state = { dark:true, nav:'Dashboard', query:'', role:'Admin', clients:[
 {clientName:'Aarav Mehta',companyName:'Urban Nest Realty',email:'aarav@urbannest.in',mobile:'+91 98765 43210',whatsApp:'+91 98765 43210',gst:'27AAFCU1209E1Z5',address:'Mumbai, Maharashtra',category:'Real Estate',website:'urbannest.in',socials:'Instagram, LinkedIn',package:'Premium Website + CRM',value:240000,advance:96000,start:'2026-07-01',deadline:'2026-08-12',team:'Riya, Kabir, Neha',status:'Development',proposal:'Accepted',progress:64,supportDays:7},
 {clientName:'Priya Sharma',companyName:'Bloom Dental Care',email:'hello@bloomdental.co',mobile:'+91 91234 56780',whatsApp:'+91 91234 56780',gst:'09BLOOM9981K2Z1',address:'Noida, Uttar Pradesh',category:'Healthcare',website:'',socials:'Facebook, Maps',package:'Business Website',value:125000,advance:50000,start:'2026-07-12',deadline:'2026-08-05',team:'Anaya, Dev',status:'Design',proposal:'Viewed',progress:32,supportDays:0},
 {clientName:'Nikhil Rao',companyName:'StackKart',email:'nikhil@stackkart.com',mobile:'+91 99887 77665',whatsApp:'+91 99887 77665',gst:'29STACK2026S1Z9',address:'Bengaluru, Karnataka',category:'Ecommerce',website:'stackkart.com',socials:'YouTube, Instagram',package:'Ecommerce Pro',value:360000,advance:360000,start:'2026-06-01',deadline:'2026-07-26',team:'Kabir, Isha, Dev',status:'Delivered',proposal:'Accepted',progress:100,supportDays:4}
]};
const tasks = [
 ['Prepare discovery proposal','Bloom Dental Care','Account Manager','High','2026-07-31',80,'Review'],['Homepage hero redesign','Urban Nest Realty','Designer','Critical','2026-08-01',55,'In Progress'],['Payment gateway testing','StackKart','Developer','Medium','2026-07-30',95,'Testing'],['SEO launch checklist','Urban Nest Realty','Developer','High','2026-08-10',20,'Todo'],['Archive handover files','StackKart','Admin','Low','2026-07-31',100,'Completed']
];
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const icon = m => ({Dashboard:'▦',Clients:'👥',Proposals:'📄',Agreements:'✅',Requirements:'⇧','Design Approval':'✦',Projects:'▤',Payments:'💳',Files:'🗂',Communication:'☎',Delivery:'✔',Support:'🛡',Reports:'⇩',Settings:'⚙'}[m]||'•');
function download(name, text, type='text/plain'){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
function pdf(name, lines){ download(`${name.replaceAll(' ','-')}.pdf`, `${name}\nThink Stack Technologies\n\n${lines.join('\n')}`, 'application/pdf'); }
function csv(){ const rows = state.clients.map(c=>[c.companyName,c.clientName,c.email,c.status,c.value,c.advance,c.value-c.advance].join(',')); download('think-stack-clients.csv', 'Company,Client,Email,Status,Value,Advance,Remaining\n'+rows.join('\n'), 'text/csv'); }
function filtered(){ const q=state.query.toLowerCase(); return state.clients.filter(c=>Object.values(c).join(' ').toLowerCase().includes(q)); }
function card(t,v){ return `<div class="card"><span>${t}</span><b>${v}</b><small>+12% vs last month</small></div>`; }
function panel(title, body){ return `<section class="panel"><h3>${title}</h3>${body}</section>`; }
function clientList(clients){ return panel('Clients & project status', `<div class="table">${clients.map((c,i)=>`<article><div><b>${c.companyName}</b><span>${c.clientName} • ${c.email}</span></div><span class="tag">${c.status}</span><span>${money(c.value-c.advance)} due</span><progress value="${c.progress}" max="100"></progress><button data-pdf="${i}">PDF</button></article>`).join('')}</div>`); }
function dashboard(){ const c=state.clients; const total=c.length, active=c.filter(x=>!['Completed','Delivered'].includes(x.status)).length, completed=c.filter(x=>['Completed','Delivered'].includes(x.status)).length, pending=c.reduce((s,x)=>s+x.value-x.advance,0), rev=c.reduce((s,x)=>s+x.advance,0); const max=Math.max(...c.map(x=>x.advance),1); return `<div class="cards">${card('Total Clients',total)}${card('Active Projects',active)}${card('Completed',completed)}${card('Pending Payments',money(pending))}${card('Monthly Revenue',money(rev))}${card('Upcoming Deadlines','5')}</div><div class="grid two">${panel('Revenue Analytics',`<div class="bars">${c.map(x=>`<div><i style="height:${(x.advance/max)*160+20}px"></i><span>${x.companyName.slice(0,10)}</span></div>`).join('')}</div>`)}${panel('Recent Activities',`<div class="list">${['Proposal viewed by Bloom Dental','Urban Nest design revised','StackKart delivery confirmed','Invoice TST-004 paid'].map((x,i)=>`<p>◷ ${x}<small>${i+1}h ago</small></p>`).join('')}</div>`)}</div>${panel('Complete agency workflow',`<div class="workflow">${workflow.map((w,i)=>`<div><b>${i+1}</b>${w}<span>›</span></div>`).join('')}</div>`)};`; }
function clientsPage(){ return `<div class="grid two">${panel('Add unlimited client',`<form id="clientForm" class="form">${['clientName','companyName','email','mobile','whatsApp','gst','address','category','website','socials','package','team'].map(k=>`<input name="${k}" ${['clientName','email'].includes(k)?'required':''} placeholder="${k.replace(/([A-Z])/g,' $1')}">`).join('')}<input name="value" type="number" placeholder="Project Value"><input name="advance" type="number" placeholder="Advance Paid"><input name="start" type="date" value="2026-07-30"><input name="deadline" type="date" value="2026-08-30"><select name="status">${statuses.map(s=>`<option>${s}</option>`)}</select><button>＋ Save Client</button></form>`)}${clientList(filtered())}</div>`; }
function kanban(){ return `<div class="kanban">${['Todo','In Progress','Review','Testing','Completed'].map(col=>panel(col,`<div class="tasks">${tasks.filter(t=>t[6]===col).map(t=>`<article><b>${t[0]}</b><span>${t[1]}</span><small>${t[2]} • ${t[3]} • ${t[4]}</small><progress value="${t[5]}" max="100"></progress></article>`).join('')}</div>`)).join('')}</div>`; }
function payments(){ return panel('Invoices, receipts and outstanding report',`<button id="csv">⇩ Export Excel</button><div class="table">${filtered().map((c,i)=>`<article><div><b>${c.companyName}</b><span>Cost ${money(c.value)} • Advance ${money(c.advance)}</span></div><span>${money(c.value-c.advance)} remaining</span><button data-invoice="${i}">Invoice PDF</button><button data-receipt="${i}">Receipt</button></article>`).join('')}</div>`); }
function reports(){ const c=state.clients, max=Math.max(...c.map(x=>x.value),1); return `<div class="grid two">${panel('Growth reports',`<div class="bars">${c.map(x=>`<div><i style="height:${(x.value/max)*160+20}px"></i><span>${x.category}</span></div>`).join('')}</div>`)}${panel('Downloads',`<button id="csv">⇩ Client Excel</button><button id="revenuePdf">⇩ Revenue PDF</button>`)}</div>`; }
function settings(){ return panel('Company, GST, banking and templates',`<div class="form"><input value="Think Stack Technologies"><input value="GST: 27ABCDE1234F1Z5"><input value="Invoice Prefix: TST-INV"><textarea>Email template: Your project update is ready.</textarea><textarea>WhatsApp template: Hello {{client}}, sharing today's progress.</textarea></div>`); }
function modulePage(nav){ const fields={Proposals:['Company Information','Client Information','Project Scope','Included Features','Excluded Features','Timeline','Pricing','Payment Terms','Terms & Conditions','Draft / Sent / Viewed / Accepted / Rejected'],Agreements:['Client Name','Project Name','Package','Timeline','Payment Terms','Ownership Clause','Support Clause','Termination Clause','Signature Section'],Requirements:['Business Information','Logo Upload','Brand Colors','Business Description','Products','Services','Images','Videos','Contact Details','Google Maps','WhatsApp','Email','Social Media','Domain','Hosting','Admin Login','Notes'], 'Design Approval':['Upload Designs','Collect Client Feedback','Approve Design','Revision History','Approval Date'],Files:['Proposal','Agreement','Invoices','Images','Videos','Documents','Source Code','Contracts','Automatic Categorization'],Communication:['Calls','WhatsApp','Emails','Meetings','Notes','History'],Delivery:['Website Live','SSL','Domain Connected','Hosting','Forms Working','WhatsApp Working','SEO Completed','Speed Tested','Responsive Tested','Admin Access','Source Code','Credentials','Delivery Date','Client Confirmation'],Support:['Support Days Remaining','Bug Reports','Fix History','Support Status']}; return `<div class="grid two">${panel(`${nav} workspace`,`<div class="checklist">${(fields[nav]||[]).map(f=>`<label><input type="checkbox"> ${f}</label>`).join('')}</div><button id="modulePdf">⇩ Export PDF</button>`)}${clientList(filtered())}</div>`; }
function render(){ document.body.className=state.dark?'dark':''; document.querySelector('#root').innerHTML = `<div class="app"><aside><div class="brand"><div class="logo">TS</div><div><b>Think Stack</b><span>Technologies</span></div></div>${modules.map(m=>`<button class="${state.nav===m?'active':''}" data-nav="${m}"><span>${icon(m)}</span><span>${m}</span></button>`).join('')}</aside><main><header><div><h1>${state.nav}</h1><p>Premium agency OS from inquiry to delivery.</p></div><div class="search">⌕<input id="search" placeholder="Search clients, projects, invoices..." value="${state.query}"></div><select id="role"><option>Admin</option><option>Developer</option><option>Designer</option><option>Account Manager</option></select><button id="theme" class="icon">${state.dark?'☀':'☾'}</button><button class="icon">🔔</button></header><section class="hero"><div><span class="pill">✦ Production-ready workflow</span><h2>Client Project Management System</h2><p>Manage leads, proposals, agreements, requirements, design approvals, Kanban tasks, payments, documents, delivery, support and reports in one SaaS-grade dashboard.</p></div><button data-nav="Clients">＋ Add Client</button></section>${state.nav==='Dashboard'?dashboard():state.nav==='Clients'?clientsPage():state.nav==='Projects'?kanban():state.nav==='Payments'?payments():state.nav==='Reports'?reports():state.nav==='Settings'?settings():modulePage(state.nav)}</main></div>`; bind(); }
function bind(){ document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.nav=b.dataset.nav; render();}); document.querySelector('#theme').onclick=()=>{state.dark=!state.dark; render();}; document.querySelector('#search').oninput=e=>{state.query=e.target.value; render();}; const form=document.querySelector('#clientForm'); if(form) form.onsubmit=e=>{ e.preventDefault(); const o=Object.fromEntries(new FormData(form).entries()); state.clients.unshift({...o,value:+o.value||0,advance:+o.advance||0,proposal:'Draft',progress:0,supportDays:0}); render();}; document.querySelectorAll('[data-pdf]').forEach((b,i)=>b.onclick=()=>{const c=filtered()[i]; pdf(`Proposal ${c.companyName}`,[`Client: ${c.clientName}`,`Scope: ${c.package}`,`Pricing: ${money(c.value)}`,`Payment Terms: ${money(c.advance)} advance`]);}); document.querySelectorAll('[data-invoice]').forEach((b,i)=>b.onclick=()=>{const c=filtered()[i]; pdf(`Invoice ${c.companyName}`,[`GST: ${c.gst}`,`Project cost: ${money(c.value)}`,`Paid: ${money(c.advance)}`,`Due: ${money(c.value-c.advance)}`]);}); document.querySelectorAll('[data-receipt]').forEach((b,i)=>b.onclick=()=>{const c=filtered()[i]; pdf(`Receipt ${c.companyName}`,[`Received from ${c.clientName}`,`Amount: ${money(c.advance)}`]);}); document.querySelectorAll('#csv').forEach(b=>b.onclick=csv); const r=document.querySelector('#revenuePdf'); if(r) r.onclick=()=>pdf('Revenue Report',state.clients.map(c=>`${c.companyName}: ${money(c.value)}`)); const m=document.querySelector('#modulePdf'); if(m) m.onclick=()=>pdf(state.nav,[`${state.nav} generated for Think Stack Technologies`,'Client information, history and status included.']); }
render();
